---
title: "Informe examen"
author: "Luis Llera García"
date: "5 de febrero de 2019"
output: pdf_document
---
# *INFORME EXAMEN 2019*
El objetivo de este informe es realizar tanto la predicción como la clasificación de nuevas observaciones en grupos en función de una serie de características, dependiendo del análisis que realicemos. Así como responder a las preguntas que se nos han realizado.

# **Executive Summary**

Por ende, vamos a realizar un análisis de regresión logística y modelo de árboles de decisión con el objetivo de finalmente compararlos y ver mediante la curva ROC o su precisión cual es el modelo que se adapta mejor a los datos, prediciendo cat2.
Nuestro conjunto de datos extraido de la *Encuesta de Presupuestos Familiares* del año 2017 elaborada por el Instituto Nacional de Estadística.
Hemos extraido de la base de datos a las variables cat2 y cat3 que han sido extraídas e incorporadas al dataset de manera independiente.

Las variables *cat2* y *cat3* explican el nivel de consumo anual de carne de vacuno de los hogares españoles. Además contamos con las siguientes variables:

| VARIABLES | DEFINICIÓN                                                                       |
|-----------|----------------------------------------------------------------------------------|
| TAMAMU    | Tamaño de los municipios                                                         |
| DENSIDAD  | Densidad de la población                                                         |
| EDAD      | Edad, expresada en años                                                          |
| SEXO      | Sexo de la muestra                                                               |
| ESTUD     | Nivel de estudios completados                                                    |
| LAB       | Situación laboral                                                                |
| REGTEN    | Regimen de tenencia de la vivienda                                               |
| SUPERF    | Superficie de la vivienda en metros cuadrados                                    |
| IMPEXAC   | Importe exacto de los ingresos mensuales netos totales del hogar en cientos de € |

Todas estas variables van a ser tratadas y renombradas para que su estudio, aplicación y comprensión sea más sencilla en los posteriores análisis que realicemos, las hemos modificado a tipo factor las categóricas y numerico o int para las numéricas.
Los ingresos se han multiplicado por 100 para que estén en numeros enteros.


# **Análisis exploratorio**
El objetivo del mismo es depurar la base de datos para que la aplicación de los dos modelos sea correcta.

Comenzamos eliminando los valores perdidos *(NA)* ya que solo nos limita unas cuantas observaciones y no influyen en el resultado global. Debido a que la variable que contiene estos valores es la *Superficie*, sería un error imputar la media o mediana de grupo ya que los datos se alterarían. Nos quedamos con un total de 4052 observaciones con las realizaremos los análisis de las 4220 originales que incluía el dataset.

Los niveles de las variables factor se han reclasificado siguiendo el esquema provisto en la hoja de excel donde por ejemplo la situación laboral eran valores entre 0 y 4 se ha incluído su verdadero valor:

- Ocupado a jornada completa
- Ocupado a jornada parcial
- Parado
- Jubilado/otros

Se ha realizado lo mismo para las demás variables y se han representado todas y cada una de ellas en función de Categoría3, para ver como influyen cada una de manera independiente, como conclusiones gráficas hemos extraido:

- El consumo de carne está relacionado con la edad, ya que a mayor edad aumenta el consumo, encontramos un outlier a partir de los 80 años.
- En cuanto a superficie e ingresos se distribuye de forma irregular, no encontrando ninguna particularidad en relación a dichas variables.
- En cuanto a la variable categórica *tamaño de municipio* está bastante desbalanceada siendo aquellos de +10000 habitantes donde se aglomera la mayor proporción. Al igual pasa con densidad de zona, lo cual tiene sentido ya que densidad implica acumulación de personas y por ende mayor consumo. 
- El sexo está mejor distribuido que las anteriores, aunque con un consumo mayor por parte de los hombres.
- En relación a los estudios el único punto más bajo se encuentra en la segunda etapa de la educación secundaria.
- La situación laboral sí que influye de manera notoria en el consumo. Tiene sentido pensar que aquella persona cuya situación laboral sea peor que otra tenderá a tener una dieta más austera evitando/consumiendo menos de este producto que en general es caro.
- En el tipo de vivienda también observamos diferencias siendo mayor el consumo en gente con un hogar estable y menos en el caso de ser alquilados o hipotecados. En este último caso vemos que el consumo medio-bajo es prácticamente inexistente, siendo lo normal un consumo muy bajo o bajo.

Aunque a priori parece que está demostrada la no normalidad de las variables, se va a realizar el test de Saphiro para corroborarlo.
Evidentemente se confirma la no normalidad de todas las variables numéricas.
*H0: Es normal*, *H1: No es normal*. 
Por tanto buscaremos rechazar la hipótesis nula, queremos que nuestros datos no sean normales.
Como se observa el p-valor alcanzado para los tres tipos de consumo de carne es muy bajo, rozando el cero, por lo tanto se rechaza la hipótesis de que es normal.
Otra premisa necesaria para estos análisis es que las variables numéricas no deben de estar muy correlacionadas entre todas debido a que ello incurre en un problema de multicolienalidad, pero analizando la matriz de correlaciones se observa que no es asi.
Además y para concluir el análisis explotorio realizaremos el test de Bartlett. En estadística, la prueba de Bartlett se utiliza para probar si k muestras provienen de poblaciones con la misma varianza. A las varianzas iguales a través de las muestras se llama homocedasticidad u homogeneidad de varianzas, es sensible a las desviaciones de la normalidad.
H0 significaría que todas las varianzas de una población k son iguales.

Por último cabe deducir que todas as variables de este modelo tienen un parámetro estimado que no es cero, con un alto nivel de confianza del 95%.

# **Modelo de regresión logística**
 
Dentro de el segundo apartado de este examen nos piden comparar el modelo de regresión logística con árboles para observar cual de los dos explica mejor la variable cat2, consumo bajo o no bajo de carne.

En este apartado buscaremos realizar un análisis de regresión logística con las variables anteriormente descritas . Y la variable a predecir será cat2. 

El modelo logit nos permite utilizar variables categóricas y numéricas indistintamente y es necesario dividir en *train* y *test* usando unos porcentajes de 80 y 20 respectivamente.

Por tanto, lo que se buscará en el siguiente análisis será realizar un modelo de regresión logística con dichos datos, utilizando como variable a explicar “cat2 consumo medio-alto, medio-bajo”, que es de tipo categórico. 
 
A través de estos modelos podemos utilizar para los mismos variables cualitativas o categóricas como es el caso de nuestra variable, fragmentaremos el total de las informaciones en 80% que será la parte de entrenamiento, y un 20% lo de dedicaremos a la parte de testeo

Recordemos que un modelo de clasificación es aquel capaz de predecir a qué clase va a pertenecer una nueva instancia, basándose en lo aprendido en instancias anteriores, por tanto, realizaremos una matriz de confusión para observar si se han clasificado bien las variables o no si existen falsos positivos o falsos negativos. Y finalmente para evaluar este modelo podríamos simplemente calcular su precisión (“accuracy”), como la proporción entre las predicciones correctas que ha hecho el modelo y el total de predicciones.

Para solucionar problemas de overfitting la variable cat3 debe de estar fuera del modelo, si no se produciría un sobre-ajuste, d ela misma manera que al predecir cat3 sacaremos cat2 del modelo.

Se define un modelo de regresión inicial que contiene todas las variables para tener una primera aproximación sobre lo que queremos realizar. Más tarde mediante la función stepAIC con el método *both* conseguiremos un modelo de regresión que cumpla el criterio de menor AIC(penaliza grados de libertad) que será con el que finalmente nos quedemos. 

Al realizar el modelo, comprobaremos la predicción con el test, y será necesario definir un *cut-off* o punto de corte a partir de las cuales, nuestras predicciones son 0 y 1.


Se emplea un algoritmo matemático para ajustar el cut-off dentro de un rango, en este caso 0.127 y 0.5 y se prueban diferentes cortes. Usando el corte en 0.48 se obtiene un accuracy del 88% lo cual es muy buen resultado.

El último paso sería la elaboración de la curva ROC (que es una representación gráfica de la sensibilidad frente a la especificidad de un sistema clasificador binario) con la cual obtenemos un valor de 93% clasificados correctamente. O de la proporción de falsos negativos y falsos positivosy un accuracy del 85.95%.

Para concluir, podríamos afirmar que este modelo es un buen modelo predictivo para esta variable, los resultados de la matriz de confusión y curva roc están muy bien desde el punto de vista de la precisión.


# **Árboles de Clasificación**

El objetivo de realizar este modelo será realizar una comparativa entre este modelo y el modelo de regresión logística para *cat2* y para lo compararemos con un arbol que clasificará *cat3* y así podremos observar si los arboles son mejores clasificadores binarios o no, para este caso.

Un árbol de decisión es un mapa de los posibles resultados de una serie de decisiones relacionadas. Permite que un individuo o una organización comparen posibles acciones entre sí según sus costos, probabilidades y beneficios. Se pueden usar para dirigir un intercambio de ideas informal o trazar un algoritmo que anticipe matemáticamente la mejor opción.

Realizaremos primeramente un arbol completo y mas tarde para evaluar su estabilidad realizaremos la poda para probar si existe *over-fitting*. Obtenemos un *accuracy* del 88% lo cual es un resultado muy bueno para nuestro arbol.

Lo representamos graficamente para poder visualizar los datos y las ramas de nuestra clasificación, cada uno de los cuadrados coloreados representa un nodo de nuestro árbol, con su regla de clasificación correspondiente, cada nodo está coloreado de acuerdo a la categoría mayoritaria entre los datos que agrupa. Esta es la categoría que ha predicho el modelo para ese grupo.

La curva ROC nos arroja un área debajo de la curva del 90% que es un resultado muy bueno, posteriormente vamos a realizar la poda que nos basaremos en los resultados del xerror, y lo aplicaremos al CP(parámetro de complejidad relativo error mínimo) y posteriormente realizamos la poda y comprobaremos que arbol de los dos es mejor.

El *accuracy* para el árbol podado con un CP del 0.22914 es mucho menos que el arbol inicial, por tanto, podemos concluir que no es necesaria la poda ya que no hay *over-fitting*.
 


## Regresión Logística VS Árboles de clasificación para *Cat2*

Ahora realizaremos la comparativa entre ambos modelos, y podemos observar que el *accuracy* que hemos obtenido con el árbol es practicamente el mismo al que hemos obtenido con regresión logística, sin embargo, el área bajo la curva(Este índice se puede interpretar como la probabilidad de que un clasificador ordenará o puntuará una instancia positiva elegida aleatoriamente más alta que una negativa) nos otorga mayores resultados con la regresión logística.

Finalmente nos quedaremos con el modelo de regresión logística ya que su AUC es mayor, y es un indicador mas general que la precisión y no depende de un hiperparámetro como si lo hace el *accuracy*
Seleccionaríamos el modelo logístico ya que el AUC o área bajo la curva es un indicar más general que la precisión y no depende de un hiperparámetro como este último.

|     Cat2  | Regresión Logistica |  Arbol de Decisión        |
|-----------|---------------------|---------------------------|
| Curva ROC | 93%                 | 90%                       | 
| Accuracy  | 88%                 | 89.06%                    |

## *Arboles con Cat3*

Las variables que hemos utilizado son todas menos cat2 debido a que incluir cat2 para predecir cat3 es absurdo ya que incurriríamos en un problema de over-fitting.
Hemos realizado la prueba realizando mediante árboles una clasificación multivariante, estos generalmente se  utilizan para clasificaciones binarias, pero hemos realizado la prueba. Como hemos podido observar el accuracy se ha reducido y la curva ROC, no la podemos hacer por que posee mas de dos niveles la variable categórica. Por tanto, hemos perdido capacidad predictiva y clasificadora, esto nos indica que si no son variables binarias nuestros resultados se ven condicionados. Si accuracy es del 35% un valor muy muy bajo.

# *Comparar y analizar los resultados obtenidos en los apartados b y c.*

Por último vamos a comparar los resultados de los apartados anteriores. Como hemos comentado previamente, los dos modelos para clasificar categoría2, nuestro modelo de regresion ogística tenían mas o menos la misma precision pero la AUC, de la curva ROC era superior claramente por tanto nos quedaríamos para con la regresion logística antes que con los árboles.

Respecto al arbol de decisión de Cat3, cabe destacar que a priori teníamos unas probabilidades del 33% no del 50, cosa que distorsiona el análisis desde el principio.

El árbol de clasificación de Categoria2 se puede confundir, consumos bajos clasificandolos como no bajos, en cambio del de cat3 tiene un numero mayor de errores ya que tiene mas niveles que el anterior, 3 en vez de 2.

El modelo logístico mejora esto, ya que si oprediccion está perfectamente definida entre falsos negativos y falsos positivos. 

Esto presenta una  ventaja clarisima desde el punto de vista de clasificación ya que las probabilidades son casi el doble de aceptar para predecir cat2 a cat3. Por tanto, nos limitaremos a realizar árboles de clasificacion para variables binarias, que tiene mucho mas sentido.
Esto podría representar una ventaja en la práctica, sin embargo, todos los modelos tienen capacidad predictiva y su selección final debe de basarse en los objetivos finales de la clasificación llevada a cabo.